version: '2'
services:
  firestore:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: 'gcloud beta emulators firestore start --host-port=0.0.0.0:8080 --project=fs-test'